---
apiVersion: v1
kind: Service
metadata:
 name: postgres-service
 labels:
  name: postgres-service
  author: hbc
spec:
 ports:
 - targetPort: 5432
   port: 5432
 selector:
  matchLabels:
   name: postgres-db-pod
   author: henry
...