---
apiVersion: v1
kind: Pod
metadata:
 name: postgres-db-pod
 labels:
  name: postgres-db-pod
  author: henry
spec:
 containers:
 - name: postgres-db
   image: postgres
   ports: 
   - containerPort: 5432
   env:
   - name: POSTGRES_PASSWORD
     value: hbc
   - name: POSTGRES_DB
     value: mydb
   - name: POSTGRES_USER
     value: hbc
...
   