---
apiVersion: v1
kind: Service
metadata: 
 name: voting-app-service
 labels:
  name: voting-app-service
spec:
 type: LoadBalancer
 ports:
 - targetPort: 80
   port: 80
 selector:
  matchLabels:
   name: voting-app-Pod
   author: henry
... 