apiVersion: v1
kind: Pod
metadata:
 name: voting-app-Pod
 labels:
  name: voting-app-Pod
  author: henry
spec:
 containers:
 - name: voting-app-container
   image: dockersamples/examplevotingapp_vote
   ports:
   - containerPort: 80